apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huntdevops-tls-cert
  namespace: huntdevops
spec:
  secretName: huntdevops-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: huntdevops.online
  dnsNames:
    - huntdevops.online
    - www.huntdevops.online