apiVersion: v1
kind: ConfigMap
metadata:
  name: huntdevops-config
  labels:
    {{- include "huntdevops.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }}
  DB_HOST: {{ .Values.backend.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.backend.env.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.env.DB_USER | quote }}
