apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.passwordSecretName }}
  labels:
    {{- include "huntdevops.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  {{ .Values.postgresql.auth.passwordSecretKey }}: {{ .Values.postgresql.auth.rawPassword | quote }}
