apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: huntdevops-project
  namespace: argocd
spec:
  description: HuntDevOps Production Application Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: huntdevops
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
